# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bluebird.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, pyqtSignal, Qt
from functools import partial

from PyQt5.QtMultimedia import QMediaPlayer
from PyQt5.QtWidgets import QListWidgetItem

from player.Player import Player
from ui.NameChooserDialog import NameChooserDialog


class ClickableWidget(QtWidgets.QWidget):
    clicked = pyqtSignal()
    data = ''

    def __init__(self, parent=None):
        super(ClickableWidget, self).__init__(parent=parent)

    def mousePressEvent(self, event):
        self.clicked.emit()

    def setUserData(self, d):
        self.data = d

    def getUserData(self):
        return self.data


class Ui_MainWindow(object):

    def select_list(self):
        self.bibliotecaBtn.setText('hola')

    def new_list(self):
        nombres_ocupados = self.player.get_playlists()
        name = NameChooserDialog().exec_()
        if (len(name.strip()) == 0 or name.isspace()):
            name = 'Nueva Lista'

        valido = False
        cont = 0
        aux = name
        while(not valido):
            if aux in nombres_ocupados:
                cont = cont+1
                aux = name + '(' + str(cont) + ')'
            else:
                valido=True
        name = aux

        self.player.guardar_playlist(name)
        self.add_list(name)


    def add_list(self, name):

        Item = ClickableWidget(self.listsContainer)
        Item.setMinimumSize(QtCore.QSize(0, 40))
        Item.setMaximumSize(QtCore.QSize(16777215, 40))
        Item.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))

        Item.setObjectName("playListItem")
        hLayout = QtWidgets.QHBoxLayout(Item)
        hLayout.setContentsMargins(0, 0, 0, 0)
        hLayout.setObjectName("horizontalLayout_2")
        Icon = QtWidgets.QPushButton(Item)
        Icon.setMinimumSize(QtCore.QSize(40, 40))
        Icon.setMaximumSize(QtCore.QSize(40, 40))
        Icon.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/carlo/Downloads/lista-de-verificacion.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        Icon.setIcon(icon2)
        Icon.setObjectName("listIcon")
        hLayout.addWidget(Icon)
        NameLabel = QtWidgets.QLabel(Item)
        font = QtGui.QFont()
        font.setPointSize(10)
        NameLabel.setFont(font)
        NameLabel.setObjectName("listNameLabel")
        NameLabel.setStyleSheet('background-color:rgba(0, 0, 0, 0);')
        NameLabel.setText(name)
        hLayout.addWidget(NameLabel)
        startPlayList = QtWidgets.QPushButton(Item)
        startPlayList.setMinimumSize(QtCore.QSize(40, 40))
        startPlayList.setMaximumSize(QtCore.QSize(40, 40))
        startPlayList.setText("")

        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/carlo/Downloads/boton-de-play.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        startPlayList.setIcon(icon3)
        startPlayList.setObjectName("startPlayList")
        startPlayList.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        startPlayList.clicked.connect(partial(self.player.reproducir_playlist, name))
        hLayout.addWidget(startPlayList)
        self.verticalLayout_3.addWidget(Item)
        Item.clicked.connect(self.select_list)
        Item.setUserData(self.player.get_playlist_content(name))

    def setupUi(self, MainWindow):
        self.player = Player()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1028, 755)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/carlo/Downloads/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow{\n"
                                 "\n"
                                 "}\n"
                                 "\n"
                                 "#songsFrame{\n"
                                 "    border:1px solid white;\n"
                                 "}\n"
                                 "\n"
                                 "#playListFrame{\n"
                                 "    border:1px solid white;\n"
                                 "}\n"
                                 "\n"
                                 "#playListBox{\n"
                                 "    border:none;\n"
                                 "}\n"
                                 "\n"
                                 "QFrame#container{\n"
                                 "    background-color:#2F2C2C;\n"
                                 "}\n"
                                 "QFrame#menu{\n"
                                 "    background-color:rgb(0, 66, 200);\n"
                                 "}\n"
                                 "\n"
                                 "QFrame#reproduciendoFrame{\n"
                                 "    background-color:black;\n"
                                 "}\n"
                                 "\n"
                                 "QLineEdit#searchText{\n"
                                 "    border:1px solid white;\n"
                                 "    border-radius:20px;\n"
                                 "    text-align:center;\n"
                                 "    padding-left:20px;\n"
                                 "    padding-right:20px;\n"
                                 "    background-color:rgb(0, 66, 200);\n"
                                 "    color:white;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton{\n"
                                 "    background-color:rgb(0, 66, 200);\n"
                                 "    border:none;\n"
                                 "    color:white;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton#addList{\n"
                                 "    background:none;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover{\n"
                                 "    background-color:rgb(0, 50, 150);\n"
                                 "}\n"
                                 "\n"
                                 "QGroupBox#playListBox{\n"
                                 "    color:white;\n"
                                 "    border-top:;\n"
                                 "}\n"
                                 "\n"
                                 "QLabel#listsLabel{\n"
                                 "    color:white;\n"
                                 "}"
                                 "ClickableWidget:hover{\n"
                                 "    background-color:black;\n"
                                 "}"
                                 )
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks | QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.container = QtWidgets.QFrame(self.centralwidget)
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setLineWidth(0)
        self.container.setObjectName("container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.container)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.menu = QtWidgets.QFrame(self.container)
        self.menu.setMinimumSize(QtCore.QSize(0, 60))
        self.menu.setMaximumSize(QtCore.QSize(16777215, 60))
        self.menu.setStyleSheet("QFrame#menu{\n"
                                "    border-bottom-left-radius:30px;\n"
                                "    border-bottom-right-radius:30px;\n"
                                "}")
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.menu)
        self.horizontalLayout.setContentsMargins(30, 0, 30, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bibliotecaBtn = QtWidgets.QPushButton(self.menu)
        self.bibliotecaBtn.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bibliotecaBtn.setFont(font)
        self.bibliotecaBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bibliotecaBtn.setObjectName("bibliotecaBtn")
        self.horizontalLayout.addWidget(self.bibliotecaBtn)
        self.favoritasBtn = QtWidgets.QPushButton(self.menu)
        self.favoritasBtn.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.favoritasBtn.setFont(font)
        self.favoritasBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.favoritasBtn.setObjectName("favoritasBtn")
        self.horizontalLayout.addWidget(self.favoritasBtn)
        self.searchText = QtWidgets.QLineEdit(self.menu)
        self.searchText.setMinimumSize(QtCore.QSize(0, 40))
        self.searchText.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(11)
        self.searchText.setFont(font)
        self.searchText.setObjectName("searchText")
        self.searchText.editingFinished.connect(self.search_songs)
        self.horizontalLayout.addWidget(self.searchText)
        self.verticalLayout_2.addWidget(self.menu)
        self.frame = QtWidgets.QFrame(self.container)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.playListFrame = QtWidgets.QFrame(self.frame)
        self.playListFrame.setMaximumSize(QtCore.QSize(500, 16777215))
        self.playListFrame.setStyleSheet("*{\n"
                                         "    color:white;\n"
                                         "    background-color:#2F2C2C;\n"
                                         "}\n"
                                         "QPushButton{\n"
                                         "    background:none;\n"
                                         "}\n"
                                         "\n"
                                         "QLabel{\n"
                                         "    color:white;\n"
                                         "}")
        self.playListFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.playListFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.playListFrame.setObjectName("playListFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.playListFrame)
        self.verticalLayout_4.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.playListFrame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.listsLabel = QtWidgets.QLabel(self.frame_2)
        self.listsLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.listsLabel.setFont(font)
        self.listsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.listsLabel.setObjectName("listsLabel")
        self.horizontalLayout_3.addWidget(self.listsLabel)
        self.addList = QtWidgets.QPushButton(self.frame_2)
        self.addList.setMinimumSize(QtCore.QSize(40, 40))
        self.addList.setMaximumSize(QtCore.QSize(40, 40))
        self.addList.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addList.setText("")
        self.addList.clicked.connect(self.new_list)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/carlo/Downloads/anadir-lista (1).png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.addList.setIcon(icon1)
        self.addList.setObjectName("addList")
        self.horizontalLayout_3.addWidget(self.addList)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.listsScroll = QtWidgets.QScrollArea(self.playListFrame)
        self.listsScroll.setWidgetResizable(True)
        self.listsScroll.setObjectName("listsScroll")
        self.scrollContents = QtWidgets.QWidget()
        self.scrollContents.setGeometry(QtCore.QRect(0, 0, 496, 514))
        self.scrollContents.setStyleSheet("")
        self.scrollContents.setObjectName("scrollContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollContents)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.listsContainer = QtWidgets.QFrame(self.scrollContents)
        self.listsContainer.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setKerning(True)
        self.listsContainer.setFont(font)
        self.listsContainer.setStyleSheet("")
        self.listsContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.listsContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.listsContainer.setObjectName("listsContainer")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.listsContainer)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.listsContainer, 0, 0, 1, 1)
        self.listsScroll.setWidget(self.scrollContents)
        self.verticalLayout_4.addWidget(self.listsScroll)
        self.listsScroll.raise_()
        self.frame_2.raise_()
        self.horizontalLayout_5.addWidget(self.playListFrame)
        self.songsFrame = QtWidgets.QFrame(self.frame)
        self.songsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.songsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.songsFrame.setObjectName("songsFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.songsFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.songsList = QtWidgets.QListWidget(self.songsFrame)
        self.songsList.setStyleSheet("background-color:rgb(47, 44, 44);\n"
                                     "color:white;\n"
                                     "border:none;")
        self.songsList.setObjectName("songsList")
        self.songsList.itemClicked.connect(self.song_selected)
        self.gridLayout_3.addWidget(self.songsList, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.songsFrame)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.reproduciendoFrame = QtWidgets.QFrame(self.container)
        self.reproduciendoFrame.setMinimumSize(QtCore.QSize(0, 80))
        self.reproduciendoFrame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.reproduciendoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.reproduciendoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.reproduciendoFrame.setObjectName("reproduciendoFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.reproduciendoFrame)
        self.horizontalLayout_2.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.reproduciendoFrame)
        self.frame_4.setStyleSheet("color:white;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelTitulo = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitulo.setFont(font)
        self.labelTitulo.setStyleSheet("color:white;")
        self.labelTitulo.setObjectName("labelTitulo")
        self.labelTitulo.setText('Título')
        self.verticalLayout_6.addWidget(self.labelTitulo)
        self.labelArtistas = QtWidgets.QLabel(self.frame_4)
        self.labelArtistas.setStyleSheet("color:grey;")
        self.labelArtistas.setText("artista")
        self.labelArtistas.setObjectName("labelArtistas")
        self.verticalLayout_6.addWidget(self.labelArtistas)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.reproduciendoFrame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pause_play = QtWidgets.QPushButton(self.frame_3)
        self.pause_play.setStyleSheet("QPushButton{\n"
                                      "    background:none;\n"
                                      "}")
        self.pause_play.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/carlo/Downloads/tocar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause_play.setIcon(icon2)
        self.pause_play.setIconSize(QtCore.QSize(40, 40))
        self.pause_play.setObjectName("pause_play")
        self.pause_play.clicked.connect(self.handle_play_pause)
        self.verticalLayout_5.addWidget(self.pause_play)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_3)
        self.horizontalSlider.setStyleSheet("\n"
                                            "")
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setProperty("value", 0)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.sliderMoved.connect(self.set_song_duration_by_slider_position)
        self.horizontalSlider.sliderPressed.connect(self.player.pausar_cancion)
        self.horizontalSlider.sliderReleased.connect(self.player.reproductor.play)
        self.verticalLayout_5.addWidget(self.horizontalSlider)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 6)
        self.verticalLayout_2.addWidget(self.reproduciendoFrame)
        self.verticalLayout.addWidget(self.container)
        self.player.reproductor.positionChanged.connect(self.update_slider)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        for element in self.player.get_playlists():
            self.add_list(element)

        for cancion in self.player.obtener_canciones():
            self.add_song_to_frame(cancion['title_short']+' ('+cancion['artist']['name']+')', cancion['preview'])

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BlueBird"))
        self.bibliotecaBtn.setText(_translate("MainWindow", "Mas Escuchadas"))
        self.favoritasBtn.setText(_translate("MainWindow", "Canciones Favoritas"))
        self.searchText.setPlaceholderText(_translate("MainWindow", "Buscar..."))
        self.listsLabel.setText(_translate("MainWindow", "Listas de Reproducción"))

    def add_song_to_frame(self, name, data=None):
        item = QListWidgetItem(name)
        item.setData(Qt.UserRole, data)
        self.songsList.addItem(item)

    def song_selected(self):
        item = self.songsList.currentItem()
        url = item.data(Qt.UserRole)
        print(url)
        self.player.reproducir_cancion(url=url)

    def search_songs(self):
        self.songsList.clear()
        for cancion in self.player.obtener_canciones_por_nombre(self.searchText.text()):
            self.add_song_to_frame(cancion['title_short']+' ('+cancion['artist']['name']+')', cancion['preview'])

    def set_song_duration_by_slider_position(self, posicion):
        # Desconectar la señal `sliderMoved` antes de establecer el valor del QSlider

        # Convertir la posición del control deslizante a milisegundos
        nueva_posicion = round(posicion  * self.player.reproductor.duration() / 100)

        # Actualizar la posición del reproductor
        if (self.player.reproductor.duration() != 0):
            self.player.reproductor.setPosition(nueva_posicion)

        # Volver a conectar la señal `sliderMoved` después de establecer el valor del QSlider

    def update_slider(self, position):
        print(position)
        # Obtener la duración del archivo multimedia
        duracion = self.player.reproductor.duration()
        if((position != 0) and (duracion !=0)):
            self.horizontalSlider.setValue(round(position * 100 / duracion))

        # Actualizar el valor del control deslizante y la etiqueta de posición
        #self.horizontalSlider.blockSignals(True)
        #self.horizontalSlider.setValue(position * 100 / duracion)
        #self.horizontalSlider.blockSignals(False)

    def handle_play_pause(self):
        if self.player.reproductor.state() == QMediaPlayer.State.PlayingState:
            self.player.pausar_cancion()
        else:
            self.player.reproductor.play()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
